# Generated by Django 3.2.3 on 2021-05-28 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productdb', '0002_alter_producto_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='stock',
            field=models.CharField(max_length=10),
        ),
    ]
