# Generated by Django 3.2.3 on 2021-05-29 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productdb', '0004_auto_20210529_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='tipo',
            field=models.CharField(max_length=15),
        ),
        migrations.DeleteModel(
            name='Tipo',
        ),
    ]
