# Generated by Django 3.2.3 on 2021-05-29 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productdb', '0005_auto_20210529_1427'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tipo',
            fields=[
                ('codigo', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
            ],
        ),
    ]
