# Generated by Django 3.2.3 on 2021-06-25 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productdb', '0010_cliente_pedido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.BooleanField(default=False),
        ),
    ]
